name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-test:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      SOLUTION: AdaskoTheBeAsT.MediatR.SimpleInjector.sln
      TEST_RESULTS_DIR: ${{ runner.temp }}\TestResults
      MSBUILDSINGLELOADCONTEXT: 1
      disable.coverage.autogenerate: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET from global.json
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\NuGet\Cache
            ~\.nuget\packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        shell: pwsh
        run: dotnet restore $env:SOLUTION --verbosity quiet

      - name: Restore .NET tools
        shell: pwsh
        run: dotnet tool restore

      - name: Install SonarScanner for .NET
        shell: pwsh
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET global tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: SonarCloud begin
        if: ${{ secrets.SONAR_TOKEN != '' }}
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          dotnet sonarscanner begin
          /k:"AdaskoTheBeAsT_AdaskoTheBeAsT.MediatR.SimpleInjector"
          /o:"adaskothebeast-github"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.cs.vstest.reportsPaths="$env:TEST_RESULTS_DIR\*.trx"
          /d:sonar.cs.vscoveragexml.reportsPaths="${{ github.workspace }}\coverage.xml"
          /d:sonar.resharper.cs.reportPath="${{ github.workspace }}\CodeQualityResults.xml"

      - name: Build
        shell: pwsh
        run: dotnet build $env:SOLUTION --configuration $env:CONFIGURATION --no-restore

      - name: Prepare results folders
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:TEST_RESULTS_DIR"
          New-Item -ItemType Directory -Path "$env:TEST_RESULTS_DIR" | Out-Null
          New-Item -ItemType Directory -Path "${{ github.workspace }}\nuget" | Out-Null

      - name: Test and collect coverage (trx + vscoveragexml)
        shell: pwsh
        run: >
          dotnet tool run dotnet-coverage collect
          "dotnet test $env:SOLUTION
          --no-restore
          --no-build
          --configuration $env:CONFIGURATION
          --logger trx
          --results-directory $env:TEST_RESULTS_DIR
          -p:RunCodeAnalysis=false
          -p:TreatWarningsAsErrors=false
          -p:TestTfmsInParallel=false"
          --settings "${{ github.workspace }}\coverage.settings.xml"
          -f xml
          -o "${{ github.workspace }}\coverage.xml"

      - name: ReSharper InspectCode
        continue-on-error: true
        shell: pwsh
        run: >
          dotnet tool run jb inspectcode
          "${{ github.workspace }}\AdaskoTheBeAsT.MediatR.SimpleInjector.sln"
          -o="${{ github.workspace }}\CodeQualityResults.xml"

      - name: SonarCloud end
        if: ${{ secrets.SONAR_TOKEN != '' }}
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end

      - name: Convert coverage to Cobertura + HTML
        shell: pwsh
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:"${{ github.workspace }}\coverage.xml" -targetdir:"$env:TEST_RESULTS_DIR\coverage" -reporttypes:"Cobertura;Html"

      - name: Publish unit test results to GitHub
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ env.TEST_RESULTS_DIR }}\*.trx

      - name: Coverage summary in job
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ env.TEST_RESULTS_DIR }}\coverage\Cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both

      - name: Upload test results and coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            ${{ env.TEST_RESULTS_DIR }}\*.trx
            ${{ env.TEST_RESULTS_DIR }}\coverage\**

      - name: Collect NuGet packages
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Path "${{ github.workspace }}" -Include "AdaskoTheBeAsT.*.nupkg","AdaskoTheBeAsT.*.snupkg" -File |
            ForEach-Object { Copy-Item $_.FullName "${{ github.workspace }}\nuget" -Force }

      - name: Upload NuGet packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: NugetPackages
          path: ${{ github.workspace }}\nuget\*

      - name: Push packages to NuGet.org
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "${{ github.workspace }}\nuget\*.nupkg" --api-key "$env:NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate